# Generated by Django 3.0.6 on 2020-09-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Колода'),
        ),
    ]
