# Generated by Django 3.0.6 on 2020-09-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_auto_20200911_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Decks_Names',
        ),
    ]
