# Generated by Django 3.0.6 on 2020-09-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_delete_decks_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
