# Generated by Django 3.0.6 on 2020-09-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_profile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
    ]
